variables = {}

variables["3j_2t"] = [
        "maxDeltaEta_jet_jet",
        #"avgDeltaR_jet_tag",
        #"avgDeltaR_jet_jet",
        "maxDeltaEta_tag_tag",
        "pT_jet_tag_min_deltaR",
        #"pT_jet_jet_min_deltaR",
        #"R1_jet",
        #"avgDeltaR_tag_tag",
        "minDeltaR_tag_tag",
        "minDeltaR_jet_jet",
        "R1_tag",
        # "H1_jet",
        # "HT_jets",
        "HT_tags",
        "jet2_pt",
        # "twist_jet_tag_max_mass",
        # "twist_jet_jet_max_mass",
        "multiplicity_higgsLikeDijet15",
        "jet3_pt",
        "ptSum_jets_leptons",
        # "H1_tag",
        "mass_jet_tag_tag_max_pT",
        "mass_jet_jet_jet_max_pT",
        "pT_tag_tag_min_deltaR",
        # "jet1_pt",
        # "mass_tag_tag_min_deltaR",
        # "mass_tag_tag_max_mass",
        # "median_mass_jet_jet",
        # "centrality_jets_leps",
        # "bjet1_pt",
        # "bjet2_pt",
        # "twist_tag_tag_max_mass",
        # "twist_tag_tag_min_deltaR",
        # "C_jet",
        # "sphericity_jet",
        "centrality_tags",
        # "transSphericity_jet",
        # "mass_higgsLikeDijet",
        # "mass_higgsLikeDijet2",
        #"H2_jet"
    ]

variables["3j_3t"] = [
        "maxDeltaEta_tag_tag",
        "maxDeltaEta_jet_jet",
        # "avgDeltaR_tag_tag",
        # "avgDeltaR_jet_tag",
        # "avgDeltaR_jet_jet",
        # "minDeltaR_jet_jet",
        "minDeltaR_tag_tag",
        "multiplicity_higgsLikeDijet15",
        "pT_jet_tag_min_deltaR",
        "pT_jet_jet_min_deltaR",
        # "pT_tag_tag_min_deltaR",
        # "R1_tag",
        #"R1_jet",
        "mass_tag_tag_max_mass",
        "mass_jet_tag_tag_max_pT",
        "mass_jet_jet_jet_max_pT",
        # "median_mass_jet_jet",
        # "centrality_tags",
        # "twist_tag_tag_max_mass",
        # "twist_jet_tag_max_mass",
        # "twist_jet_jet_max_mass",
         "mass_higgsLikeDijet",
        # "mass_higgsLikeDijet2",
        # "centrality_jets_leps",
        # "H1_jet",
        # "H1_tag",
        # "mass_tag_tag_min_deltaR",
        # "mass_jet_tag_min_deltaR",
        # "mass_jet_jet_min_deltaR",
        "jet3_pt",
        # "C_jet",
        # "C_tag",
        # "sphericity_tag",
        # "sphericity_jet",
        "H2_jet",
        "H2_tag",
        "HT_tags",
        # "HT_jets",
        "jet2_pt",
        # "D_jet"
    ]

variables["ge4j_2t"] = [
        "N_btags_Loose",
        "btagDiscriminatorAverage_untagged",
        "avgDeltaR_jet_tag",
        # "avgDeltaR_jet_jet",
        # "maxDeltaEta_jet_jet",
        "maxDeltaEta_tag_tag",
        "pT_tag_tag_min_deltaR",
        # "ptSum_jets_leptons",
        "pT_jet_tag_min_deltaR",
        "avgDeltaR_tag_tag",
        # "minDeltaR_tag_tag",
        # "jet5_pt",
        # "jet5_btag",
        # "jet5_eta",
        # "R1_tag",
        # "jet1_btag",
        # "HT_jets",
        # "jet4_btag",
        # "pT_jet_jet_min_deltaR",
        # "H1_tag",
        # "jet3_btag",
        # "jet4_pt",
        # "jet3_pt",
        # "H2_jet",
        "mass_jet_tag_tag_max_pT",
        # "R2_jet",
        "minDeltaR_jet_jet",
        # "lepton1_pt",
        # "jet2_pt",
        "multiplicity_higgsLikeDijet15",
        # "H4_jet",
        # "jet2_btag",
        # "H0_jet",
        # "D_jet",
        "centrality_jets_leps",
        "HT_tags",
        "mass_tag_tag_min_deltaR",
        "mass_tag_tag_max_mass",
        # "jet1_pt",
        "mass_jet_tag_min_deltaR"
]

variables["ge4j_3t"] = [
        "MEM",
        "maxDeltaEta_tag_tag",
        "blr",
        #"blr_transformed",
        # "maxDeltaEta_jet_jet",
        "avgDeltaR_tag_tag",
        #"avgDeltaR_jet_jet",
        #"avgDeltaR_jet_tag",
        #"D_tag",
        #"aplanarity_tag",
        "mass_tag_tag_max_mass",
        # "R2_tag",
        # "H2_tag",
        # "D_jet",
        # "centrality_tags",
        #"mass_tag_tag_min_deltaR",
        "centrality_jets_leps",
        #"mass_jet_tag_tag_max_pT",
        "aplanarity_jet",
        #"mass_jet_jet_jet_max_pT",
        "multiplicity_higgsLikeDijet15",
        #"C_tag",
        # "sphericity_tag",
        #"R2_jet",
         "mass_jet_tag_min_deltaR",
        #"C_jet",
        "mass_jet_jet_min_deltaR",
        "sphericity_jet",
        # "median_mass_jet_jet",
        "transSphericity_tag",
        #"H2_jet",
        # "minDeltaR_jet_jet",
        # "twist_tag_tag_max_mass",
        # "transSphericity_jet",
        # "mass_higgsLikeDijet2",
        # "mass_higgsLikeDijet",
        # "twist_jet_jet_max_mass",
        "minDeltaR_tag_tag",
        "pT_tag_tag_min_deltaR",
        "btagDiscriminatorAverage_tagged"
    ]

variables["ge4j_ge4t"] = [
        "MEM",
        "maxDeltaEta_tag_tag",
        "blr",
        #"blr_transformed",
        "maxDeltaEta_jet_jet",
        "avgDeltaR_tag_tag",
        "avgDeltaR_jet_jet",
        #"avgDeltaR_jet_tag",
        #"D_tag",
        #"aplanarity_tag",
        "mass_tag_tag_max_mass",
        #"R2_tag",
        #"H2_tag",
        #"D_jet",
        #"centrality_tags",
        #"mass_tag_tag_min_deltaR",
        "centrality_jets_leps",
        "mass_jet_tag_tag_max_pT",
        #"aplanarity_jet",
        #"mass_jet_jet_jet_max_pT",
        #"multiplicity_higgsLikeDijet15",
        #"C_tag",
        #"sphericity_tag",
        #"R2_jet",
        "mass_jet_tag_min_deltaR",
        #"C_jet",
        #"mass_jet_jet_min_deltaR",
        #"sphericity_jet",
        #"median_mass_jet_jet",
        "transSphericity_tag",
        #"H2_jet",
        "minDeltaR_jet_jet",
        # "twist_tag_tag_max_mass",
        # "transSphericity_jet",
        # "mass_higgsLikeDijet2",
        # "mass_higgsLikeDijet",
        # "twist_jet_jet_max_mass",
        "minDeltaR_tag_tag",
        "pT_tag_tag_min_deltaR",
        "btagDiscriminatorAverage_tagged"
]

variables["ge4j_ge3t"] = [
    'MEM',
    'blr',
    #'blr_transformed',
    'btagDiscriminatorAverage_untagged',
    'N_btags_Loose',
    'ptSum_jets_leptons',
    'pT_jet_tag_min_deltaR',
    'pT_jet_jet_min_deltaR',
    'maxDeltaEta_jet_jet',
    'jet3_btag',
    'HT_jets',
    'pT_tag_tag_min_deltaR',
    'jet1_pt',
    'avgDeltaR_jet_tag',
    'avgDeltaR_jet_jet',
    'R1_jet',
    'jet3_pt',
    'R1_tag',
    'H1_jet',
    'HT_tags',
    'jet2_pt',
    'H1_tag',
    'lepton1_pt',
    'maxDeltaEta_tag_tag',
    'avgDeltaR_tag_tag',
    'minDeltaR_tag_tag',
    'dilepton_pt',
    'mass_jet_tag_min_deltaR',
    'mass_jet_jet_min_deltaR',
    'bjet1_pt',
    'minDeltaR_jet_jet',
    'bjet2_pt',
    'met_pt',
    'twist_jet_tag_max_mass',
    'twist_jet_jet_max_mass',
    'multiplicity_higgsLikeDijet15',
    'mass_tag_tag_max_mass',
    'mass_higgsLikeDijet',
    'mass_tag_tag_min_deltaR',
    'mass_jet_jet_jet_max_pT',
    'mass_jet_tag_tag_max_pT'

    ]

variables["jets"]= [

    "jet1_pt",
    "jet1_eta",
    "jet1_phi",
    "jet1_M",
    "jet1_btag",

    "jet2_pt",
    "jet2_eta",
    "jet2_phi",
    "jet2_M",
    "jet2_btag",

    "jet3_pt",
    "jet3_eta",
    "jet3_phi",
    "jet3_M",
    "jet3_btag",

    "jet4_pt",
    "jet4_eta",
    "jet4_phi",
    "jet4_M",
    "jet4_btag",

    "jet5_pt",
    "jet5_eta",
    "jet5_phi",
    "jet5_M",
    "jet5_btag",

    "jet6_pt",
    "jet6_eta",
    "jet6_phi",
    "jet6_M",
    "jet6_btag",

    "bjet1_pt",
    "bjet1_eta",
    "bjet2_pt",
    "bjet2_eta",
    "bjet3_pt",
    "bjet3_eta",
    "bjet1_btag",
    "bjet2_btag",
    "bjet3_btag",
]

variables["all"] = [
     "lepton1_pt",
     "lepton2_pt",

     "lepton1_eta",
     "lepton2_eta",

      "jet1_pt",
      "jet2_pt",
      "jet3_pt",
      "jet4_pt",
      "jet5_pt",
      "jet6_pt",
      "bjet1_pt",
      "bjet2_pt",
      "bjet3_pt",
      "bjet4_pt",

      "jet1_eta",
      "jet2_eta",
      "jet3_eta",
      "jet4_eta",
      "jet5_eta",
      "jet6_eta",
      "bjet1_eta",
      "bjet2_eta",
      "bjet3_eta",
      "bjet4_eta",

      "jet1_btag",
      "jet2_btag",
      "jet3_btag",
      "jet4_btag",
      "jet5_btag",
      "jet6_btag",
      "bjet1_btag",
      "bjet2_btag",
      "bjet3_btag",
      "bjet4_btag",

     "dilepton_pt",
     "dilepton_eta",
     "dilepton_M",

     "met_pt",
     "met_phi",


     "multiplicity_higgsLikeDijet15",

     "btagDiscriminatorAverage_tagged",
     "btagDiscriminatorAverage_untagged",

     "sphericity_jet",
     "sphericity_tag" ,

     "aplanarity_jet",
     "aplanarity_tag",


     "isotropy_jet",
     "isotropy_tag",

     "C_jet",
     "C_tag",

     "D_jet",
     "D_tag",

     "transSphericity_jet",
     "transSphericity_tag",

     "H0_jet",
     "H1_jet",
     "H2_jet",
     "H3_jet",
     "H4_jet",

     "H0_tag",
     "H1_tag",
     "H2_tag",
     "H3_tag",
     "H4_tag",

     "R1_jet",
     "R2_jet",
     "R3_jet",
     "R4_jet",

     "R1_tag",
     "R2_tag",
     "R3_tag",
     "R4_tag",

     "avgDeltaR_jet_jet",
     "avgDeltaR_jet_tag",
     "avgDeltaR_tag_tag",

     "centrality_jets_leps",
     "centrality_tags",

     "circularity_jet",
     "circularity_tag",

     "mass_higgsLikeDijet",
     "mass_higgsLikeDijet2",


     "mass_jet_jet_min_deltaR",
     "mass_jet_tag_min_deltaR",
     "mass_tag_tag_min_deltaR",
     "mass_tag_tag_max_mass",
     "mass_jet_jet_jet_max_pT",
     "mass_jet_tag_tag_max_pT",

     "maxDeltaEta_jet_jet",
     "maxDeltaEta_tag_tag",

     "median_mass_jet_jet",

     "minDeltaR_jet_jet",
     "minDeltaR_tag_tag",

     "pT_jet_jet_min_deltaR",
     "pT_jet_tag_min_deltaR",
     "pT_tag_tag_min_deltaR",

     "ptSum_jets_leptons",

     "HT_jets",
     "HT_tags",

     "twist_jet_jet_max_mass",
     "twist_jet_tag_max_mass",
     "twist_tag_tag_max_mass",
     "twist_tag_tag_min_deltaR"
]

#variables["ge4j_ge3t"] = list(set(variables["ge4j_ge4t"][,] + variables["ge4j_3t"][,]))
#variables["ge4j_ge3t"] = list(set(variables["ge4j_ge4t"][,] + variables["ge4j_3t"][,] + variables["jets"]))
#!! variables["ge4j_ge3t"] = ["jet1_pt", "jet2_pt"] #!!!!

all_variables = set( [v for key in variables for v in variables[key] ] )
